### ISSUE TITLE
Should speed up be activated when Key is pressed down or should it be toggled

### ISSUE THREAD

**Issue by pylirious** [worldofjoni/BuildomASCII#81]
Reason for this question: SHIFT can **only** be detected in toggle mode. 
Furthermore, the user could get confused with the Buttons because of using the [Stand Still ability](https://github.com/worldofjoni/BuildomASCII/issues/65) and the [Time-speed](https://github.com/worldofjoni/BuildomASCII/issues/77) at the same time.

**Comment by worldofjoni** [comment]
The following term works for me without any problem...
![image](https://user-images.githubusercontent.com/47496388/58712799-9730df00-83c1-11e9-9fa3-ea05e0442671.png)
so i would only activate on press
